### ISSUE TITLE
Is there a way to prevent word wrapping?

### ISSUE THREAD

**Issue by danielrob** [pc035860/angular-highlightjs#43]
I've tried doing such things as 

div[hljs] {
  overflow: auto;
  word-wrap: none;
  white-space: pre;
}

but I can't force hljs to not word-wrap the contents of the div (I want horizontal scrollbars like you have on the readme displayed in github) any ideas?

Thanks!

**Comment by pc035860** [comment]
Hi @danielrob 

All you need is adding

```css
.hljs {
  white-space: pre;
  word-wrap: normal;
}
```

The `hljs` class is added on `<code>` element by default with highlightjs
